language: python
python:
- '3.6'
install:
- pip install .
script:
- python setup.py bdist_wheel sdist
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: __token__
  password:
    secure: cfipuyMB1SMFPE/aAo2ZvFq3DMO/J4lKViA1+BJBgjy1zz/BcRK8k6xqkFw2jIPyrjqlWh+ztPeffUzjiLGJbVzQ07AkKhrUsHwYahMsL46bAambLPDXVJB+mauhhInOSw+M8m5xzNlVa9auNMhgwspmInbj9BsHFih3Nk5BeGrREEA4zzRcecMtlfoIWxvpECDQro4C1jRhTpLVCyHAUqiZu+3cGvUNIwuul0YV4upR0PqJrtZ4slMtWTZAfOsKF2oGXkMVUiONSRXOeF/14/8yi5qL2uhtJnN3u0FxjUVFVEZyM/s8pFPLpYk68uZOyZuY6TyT/7LxHqhthXSIVpvUelaf/iwNXrwupNMAB5WkNIXgyzy9qmJ5hoiOfj2Yx9MXVcyct3T+b380X78n7lh0lY7ogyubQaxM+bBr/Hy92B4wwUWa4bCAKuLVeoLxpRve8zD4mZrnO1cj0r5Av9NQrFrF/kC8eDtdVc4vwIlxcN73rI52jBxxEO8bnh+QURyMDPrUd1s4CK6MsdBTyNAE9q6DJTQ+ayxmd3b19WFw6ql2cx+L2MP7tHVUkcloctp7w2eCwHDnr2JaG0/7JRa7XBMRZJOjOm8OgHGLpePlPQczXaDgbOndeFFCIKXvwaHgC1eosHVgR1Z8bXnUNLhohQFN4qRK1wdqY9FIEsE=
  skip_cleanup: true
  on:
    tags: false
  skip_existing: false

