--- 
jobs: 
  include: 
    - 
      language: python
      name: "Linux - Python 3.6"
      os: linux
      python: 
        - "3.6"
    - 
      before_install: 
        - "choco install python --version 3.8"
        - "python --version"
        - "python -m pip install --upgrade pip"
        - "pip3 install wheel || pip install wheel"
      env: "PATH=/c/Python38:/c/Python38/Scripts:$PATH"
      language: shell
      name: "Windows - Python 3.8"
      os: windows
