language: python
python:
- '3.6'
install:
- pip install .
script:
- python setup.py bdist_wheel sdist
deploy:
  provider: pypi
  user: __token__
  password:
    secure:
  skip_cleanup: true
  on:
    tags: true
  skip_existing: true

