language: python
python:
- '3.6'
install:
- pip install .
script:
- python setup.py bdist_wheel sdist
deploy:
  provider: pypi
  user: __token__
  password:
    secure: l0B82Pu/BnmR6BwwMtrCSE4hI312iQT943wEyq/zvTK+dUwhbNaGzrYXL331US5d225F4XICQ9v9SlZ92VePDzY1fq/BwG23d2/Lf+BwQnEKX5qsVhGUW6sfq6kqlrozTD9T3sc0E8rzGU3KLFSrHWnDbp+ueCgZxtpIAh0GEwosZSkYO0/woyRCeZ+8iYl43xBlP3ThN94bcBJYpBLoBSQJ66tm7S5CR84+xe2YFn0zsaFdbrn9roEW6OqRp8hfQN7turUiRST/n6szD3/V3oTEUSrQUcxqgQydAu0zz3OyIRKS8S1s/j+1SQaqwEvNQd9IAzf9OGMeTPb0JG9zIBmV9huds8FO287HA6qHlvptic+BTUPSwz39nH8VcVcvfW1D54ZED/19SuOw2pb4n2AaLc5PdTKLxI9B4XcjCTL8tyIX/hTSt//0lRB1K/wHDryjSitKsD1rYD8wuV+QWzov7mfjkkejX8EtDXwYfsZOQyvvvHgPfD0IPB9FM5Xyfm/WtwxG3m2q0HeKv58rBraWpQMC76BRq3f1J24Cin5bz+evO8/JTNT6X+UTixuDT6xMZloZiulHsnBsd8m68vuHDDsA91cIlaeh0J5Nq3wO/cyvCn45josZQ/cpY9Tingxp4ygxRlRtq2Xf28ubdw76UUkmw4qov11pKk59XGw=
  skip_cleanup: true
  on:
    tags: true
  skip_existing: true

