
name: Test mef_tools

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
            - os: ubuntu-latest
              python-version: '3.6'
#            - os: ubuntu-latest
#              python-version: '3.7'
#            - os: ubuntu-latest
#              python-version: '3.8'
#            - os: ubuntu-latest
#              python-version: '3.9'
#            - os: ubuntu-latest
#              python-version: '3.10'
#
#            - os: macos-latest
#              python-version: '3.6'
#            - os: macos-latest
#              python-version: '3.7'
#            - os: macos-latest
#              python-version: '3.8'
#            - os: macos-latest
#              python-version: '3.9'
#            - os: macos-latest
#              python-version: '3.10'
#
#            - os: windows-latest
#              python-version: '3.6'
#            - os: windows-latest
#              python-version: '3.7'
#            - os: windows-latest
#              python-version: '3.8'
#            - os: windows-latest
#              python-version: '3.9'
#            - os: windows-latest
#              python-version: '3.10'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install numpy


    - name: Test package
      run:
        python setup.py unittest
#        pip install .
#        python -m unittest
